repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: .env/bin/mypy
        language: system
        types: [ python ]
        files: ^(app/|tests/)
        args: [--no-strict-optional, --ignore-missing-imports]
      - id: black
        name: black
        entry: .env/bin/black
        language: system
        types: [ python ]
        files: ^(app/|tests/)
      - id: isort
        name: isort
        entry: .env/bin/isort
        language: system
        types: [ python ]
        exclude: '.*/migrations/.*'
        args: [
            '--line-length=110',
            '--multi-line=3',
            '--force-grid-wrap=0',
            '--trailing-comma',
            '--use-parentheses',
            '--ensure-newline-before-comments',
        ]
      - id: flake8
        name: flake8
        entry: .env/bin/flake8
        language: system
        types: [ python ]
        files: ^(app/|tests/)
